apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: uc1wesb36-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:cdfb3b8ed64f16a712cdd94b5400c4afc5f35981@sha256:67e0cd827fbafacb7eb55d8fcab2153b6bb6310faad6cf12ba68a7507a799d92
          name: container-image
